### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by ebarnette** [RoboJackets/software-training#10]
@jgkamat can you move everything but CI and the README to a file in slides called config?

**Comment by jgkamat** [comment]
Hmm, I feel like this would be counter intuitive, since it would break peoples existing workflows (build happens in the project root).

It also goes against the current standard of how gh projects are layed out (build happens at the root, dependency files such as gemfiles/requirements are at the root, etc). Are you sure this is a good idea?

**Comment by ebarnette** [comment]
We wanted to use a different repo for the code base because the slides took more config than we all originally thought. We settled on using one repo with slides and code as the top level directories and basically treating them as separate repos in one....so it makes it harder for us but much easier in the long run (so freshlings don't need to keep track of two separate repos).

afaik everyone is on the same page so if you can list what things need to be changed we can all do that asap.

**Comment by ebarnette** [comment]
Changed as in what things we need to adjust since it'll break workflows for a little

**Comment by jgkamat** [comment]
hmm, if you say so :/. I feel like this will be more confusing rather than less, though (since it goes against the standard for what you see everywhere else). I'll go ahead with it though.

**Comment by ebarnette** [comment]
Also can you give me a fancy schmancy "week1" folder name instead of just "1"?

please and thank you you're the best

**Comment by ebarnette** [comment]
Also yeah we all agreed that we're not exactly setting a good standard for how repos should run....but it's the best compromise to solve a lot of the problems popping up

**Comment by ebarnette** [comment]
pls close this when you've confirmed nothing is broken so I can know I'm good to make branches for new work.

**Comment by jgkamat** [comment]
Everything LGTM, only a README failure (#12). Let me know if you spot issues though, but everything should work as expected.
