### ISSUE TITLE
Speaker notes aren't working

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/software-training#20]
Pressing `S` on a slideshow opens a popup but the HTML source is displayed rather than the page content.

Tested on latest Chrome and Edge on latest Windows.

**Comment by jgkamat** [comment]
Speaker notes have never worked for me on reveal js, regardless of the export method or version. Even the live demo does not have working speaker notes. If you find a reveal js slide deck with working speaker notes, I could take a look at this, but I think they are just broken on reveal's end.

**Comment by kberzinch** [comment]
Okay. It worked on my local machine, I'll fiddle with it.

**Comment by jgkamat** [comment]
Maybe upgrading the reveal version will help, the path is defined near the top of the config file. Right now we're using 3.0.0 since it's publicly available on a cdn, but we can vendor our own if it fixes the issue.

**Comment by kberzinch** [comment]
I think it's some issue with headers from the CDN but I'll investigate more today or tomorrow.

**Comment by kberzinch** [comment]
I'm guessing it's because jsdelivr doesn't add a `Content-Type` header...That's fine for what they're trying to do but inconvenient for us.

Code-wise it's fine, we just need that file hosted somewhere that sets `Content-Type` correctly. Ideas?

**Comment by jgkamat** [comment]
Easy solution is to just self host it ourselves I guess, I could work on that. Would self-hosting it on github set our content-type correctly?

**Comment by kberzinch** [comment]
Yup, I just double-checked.

**Comment by jgkamat** [comment]
So, we can either host it in this repo, or we can create a separate repo just for hosting revealjs (which we can update for multiple rj repos). I like the second because it wouldn't grow this repo, but I like the first because it's less complicated. What are your thoughts?

**Comment by kberzinch** [comment]
Separate repo, I think.

**Comment by jgkamat** [comment]
I've backported a version of the week two slides to test this. @kberzinch can you make sure everything is looking good to you (and then I'll update master to point to this):
https://robojackets.github.io/software-training/slides/week2/week2.html

Also, I updated our reveal to 3.4.1, so there's a chance of breakage there.

**Comment by kberzinch** [comment]
Looks good to me!
