### ISSUE TITLE
Virtual Machine image needs updating

### ISSUE THREAD

**Issue by rpersons1** [RoboJackets/software-training#218]
#software-training/VirtualMachine_Instructions.org

Please update the virtual machine image you provided for Vitural box or for VMware, w/ ROS2 humble.
Hello, I am part of the mate ROV team at CSU Chico. These are awesome tutorials. My progress on these tutorials has been challenged by build errors and this is preventing my from recommending your coarse to other students. I was also having trouble with "Color-based Obstacle Detection" lab virtual camera not updating in Rvis with the solution code.

**Comment by barulicm** [comment]
Thanks for your interest in our course. We are in the middle of editing the projects and upgrading them to Humble in preparation for the fall semester. This will include new setup instructions for a variety of virtual machine technologies.

Our Fall 2022 course is scheduled to start on September 18th, so things should be ready by then.

**Comment by barulicm** [comment]
Updated instructions are available in [setup_instructions/readme.md](https://github.com/RoboJackets/software-training/blob/main/setup_instructons/readme.md)
