### ISSUE TITLE
Unexpected nested tag(s) all projects launch .xml

### ISSUE THREAD

**Issue by rpersons1** [RoboJackets/software-training#219]
Running: Ubuntu 22.04, ROS Humble, bash

Error msgs:

ros2 launch rj_training_bringup week_1.launch.xml    For weeks: 1,3,5,6,8
* [ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [xml]: Unexpected nested tag(s) found in `include`: {'param'}

ros2 launch rj_training_bringup week_2.launch.xml    For weeks: 2,4,7
* [ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [xml]: Unexpected nested tag(s) found in `node`: {'arg'}

**Comment by barulicm** [comment]
These have been fixed in the corresponding pull requests for each week's project. They should all work from the main branch once those PRs have been merged.

**Comment by barulicm** [comment]
The relevant PRs have been merged, so this should be resolved now.
