### ISSUE TITLE
WSL Setup Instructions command does not work for everyone

### ISSUE THREAD

**Issue by idale0001** [RoboJackets/software-training#223]
The command 
```
wsl --install --distribution Ubuntu-22.04 
```
in the WSL setup instructions does not work for many people. It says something about distribution not found. Will try to update issue with exact error if I can replicate.
Currently having people use [this guide ](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support#1-overview) because that seems to work for people.

**Comment by barulicm** [comment]
I think running with the update flag first might fix this.

```
wsl --update
wsl --install --distribution Ubuntu-22.04
```

The update command should grab the latest backend stuff from the MS store.

**Comment by idale0001** [comment]
I just tried this with a roboracing new member and the update command did not seem to work

**Comment by idale0001** [comment]
Looks like the issue is that people need to enable Virtual Machine Platform in Windows Features

**Comment by barulicm** [comment]
Cool. If you've found a sequence that works, could you update the setup instructions for WSL?

**Comment by MukilanKarthikeyan** [comment]
Setup instructions for WSL has been updated -> should work (windows 11 comes installed with wsl, if not instructions are linked. 
new file isaac_ROS_WSL.md has been created to setup Nvidia's Isaac Ros dev container via wsl has been added.

**Comment by MukilanKarthikeyan** [comment]
making comment to close issue. If future problems arise, please create a new issue.
