### ISSUE TITLE
Issue with Colcon Build on Software Training on Docker

### ISSUE THREAD

**Issue by Andrew20241** [RoboJackets/software-training#227]
Command I am running: `~/rj_training_container/training_ws $ colcon `build`
`
Starting >>> joystick_msgs
Starting >>> astar_path_planner              
Starting >>> controllers                                     
Starting >>> coordinate_transform                            
Starting >>> keyboard                                        
Starting >>> localization                                    
Starting >>> mapping                                         
Starting >>> mineral_deposit_tracking                        
Starting >>> obstacle_detector                               
Starting >>> peak_finder                                     
Starting >>> rj_training_bringup
Starting >>> teleop                                           
--- stderr: coordinate_transform                                    
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "Findstsl_interfaces.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "stsl_interfaces", but CMake did not find one.

  Could not find a package configuration file provided by "stsl_interfaces"
  with any of the following names:

    stsl_interfacesConfig.cmake
    stsl_interfaces-config.cmake

  Add the installation prefix of "stsl_interfaces" to CMAKE_PREFIX_PATH or
  set "stsl_interfaces_DIR" to a directory containing one of the above files.
  If "stsl_interfaces" provides a separate development package or SDK, be
  sure it has been installed.

---
Failed   <<< coordinate_transform [4.77s, exited with code 1]
Aborted  <<< peak_finder [4.27s]
Aborted  <<< mineral_deposit_tracking [4.50s]
Aborted  <<< mapping [4.68s]                     
Aborted  <<< localization [4.91s]                
Aborted  <<< keyboard [5.22s]                    
Aborted  <<< teleop [4.60s]
Aborted  <<< astar_path_planner [5.66s]          
Aborted  <<< joystick_msgs [5.80s]
Aborted  <<< controllers [5.72s]                 
Aborted  <<< obstacle_detector [5.19s]
Aborted  <<< rj_training_bringup [5.73s]

Summary: 0 packages finished [9.04s]
  1 package failed: coordinate_transform
  11 packages aborted: astar_path_planner controllers joystick_msgs keyboard localization mapping mineral_deposit_tracking obstacle_detector peak_finder rj_training_bringup teleop
  4 packages had stderr output: coordinate_transform localization mineral_deposit_tracking peak_finder
  1 package not processed
`

**Comment by barulicm** [comment]
To build and run the code in this repository, you will also need the packages from [stsl](https://github.com/robojackets/stsl). You can clone the source for these packages into your same colcon workspace to build them alongside the packages from this repo.

Your colcon workspace should look like this:

```
training_ws
└ src
  ├ software-training (this repo)
  └ stsl
```

**Comment by MukilanKarthikeyan** [comment]
Hi Matt! Thanks for answering the question, we fixed day of and forgot to close issue. I have updated setup.sh to appropriately clone the directory. And note added in docker.md
