### ISSUE TITLE
Missing Information in Project 3: "3.11 Add parameter to launch file"

### ISSUE THREAD

**Issue by SSPolisetti** [RoboJackets/software-training#232]
---
name: Project 3: "3.11 Add parameter to launch file"
about: About missing information in Project 3
title: "Missing Information in Project 3: "3.11 Add parameter to launch file"
---

## Description
In the section "3.11 Add parameter to launch file", there is a student code section that isn't mentioned where three imports are required in the "particle_filter_localizer.launch.py" file.

```python
# BEGIN STUDENT CODE
import os
from ament_index_python.packages import get_package_share_directory
from launch.substitutions import LaunchConfiguration
# END STUDENT CODE
```
These imports are required to use os.path.join(), get_package_share_directory, and LaunchConfiguration() in the launch file. 

## Steps to Reproduce
1. Don't include imports listed above when testing and run colcon build
2. Run "ros2 launch rj_training_bringup week_3.launch.xml"

## Expected behavior
The particle filter is supposed to launch in rviz with no errors.

## Screenshots
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/334808aa-f0f6-4ba3-be55-b1a886062255">
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/11b91924-78cd-4d03-91ff-6a4addde86c8">

**Comment by MukilanKarthikeyan** [comment]
fixed in #233
