### ISSUE TITLE
Add a few notes about hotkeys to week 1

### ISSUE THREAD

**Issue by kberzinch** [RoboJackets/software-training#38]
Ctrl+R
up/down arrow keys
tab completion

**Comment by jgkamat** [comment]
Full keybinds are in the readline documentation: http://manpages.ubuntu.com/manpages/xenial/en/man3/readline.3readline.html

**Comment by kberzinch** [comment]
@jgkamat Are there any I didn't list that you find particularly useful day to day? I want to keep this list short.

**Comment by jgkamat** [comment]
I think it's worthwhile to include:

```
"C-A"  beginning-of-line
"C-E"  end-of-line
"C-U"  unix-line-discard
"C-N"  next-history
"C-P"  previous-history
"C-W"  unix-word-rubout
"M-B"  backward-word
"M-F"  forward-word
```

although, the kind of person who would use keybinds at all would be one who would find out how to look them up, or ask about them.

Although, you should talk about `C-c` and `C-z` since people get bit by them and/or need them.

**Comment by kberzinch** [comment]
Good points. I'll definitely add the last two.

**Comment by jgkamat** [comment]
Oh, also include `Ctrl-D`, its useful and people get burned by it occasionally
