### ISSUE TITLE
Week 0 improvements

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/software-training#66]
The week 0 session needs significant change

1. more examples of using code. Teach a concept then apply it
2. More slides on how loops work
3. more slides on how scope works with relevant examples
4. detail examples of programs to write at the end
5. a more definitive plan of what should happen after we push through the slide deck
6. A way to slow down the slides so that those that do not know everything do not get lost
7. change the programming mistakes screen and just talk about general things we have done, the ones we have are too specific and only funny if you know programming already
8. a way to advertise this session so that only those without any programming experience come

**Comment by JasonGibson274** [comment]
@kberzinch add anything else that you thought would be helpful

**Comment by kberzinch** [comment]
I think that covers everything
