### ISSUE TITLE
CircleCI for new training challenge

### ISSUE THREAD

**Issue by chachmu** [RoboJackets/software-training#92]
@jgkamat Would it be possible to set up a repo where we have people push their answer to a coding challenge as a pull request and have circle ci test it? This would allow for people to get experience and feedback with both coding and git while not having to wait for a person to grade it.

**Comment by jgkamat** [comment]
the tough bit is getting the build system to automatically recognize new code and build it (esp if we want submissions to be easy to do). Once that part is done, buildnig it is trivial.
